# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

#     - name: Build with Gradle
#       run: ./gradlew build

    # Extra step requied for private beta
    - name: Checkout the action from a private repository
      uses: actions/checkout@v2
      if: ${{ always() }}
      with:
        repository: vijejain/cicd-actions-bugbash
        ref: refs/heads/main
        token: ${{ secrets.TOKEN }}
        path: ./.github/vijejain/cicd-actions-bugbash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ always() }}
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        
    - name: Before - Log the amount of space being used
      run: |
        sudo df -h
    - name: AWS CodeGuru Reviewer
      uses: ./.github/vijejain/cicd-actions-bugbash
      if: ${{ success() }}
      with:          
        build_path: target # build artifact(s) directory
        s3_bucket: codeguru-reviewer-xxz-data
        
    - name: After - Log the amount of space being used
      run: |
        sudo df -h
        
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: sarif_results
        path: codeguru-results*.json

    - name: Upload review result
      if: ${{ success() }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json
